### ISSUE TITLE
Menus have no keyboard selection indicators - but only on no-italics theme (+ possible fix?)

### ISSUE THREAD

**Issue by tallpants** [sdras/night-owl-vscode-theme#146] opened 2018-10-03 17:35 UTC
This happens on every menu that isn't the main Cmd + Shift + P menu.

An example is the recents menu (^ + R / Ctrl + R on macOS. Not sure about the equivalent shortcut on Windows).

Try pressing up / down on the keyboard to move around the menu -- the selection indicators are missing. Mousing over them makes the text bold which is a good indicator, but only selecting them with the keyboard does nothing.

This is only on the no-italics version of the theme. The regular theme has it just fine -- so I'm guessing this is a key that's on the regular theme but hasn't been copied to the no-italics theme.

It might be `"list.focusBackground"` but I'm not sure.

GIF showing the issue:
![screenflow](https://user-images.githubusercontent.com/15325890/46428091-b5760a80-c760-11e8-926a-97b487e5b554.gif)

**Comment by svipben** [comment] 2018-10-05 07:29
Duplicate of https://github.com/sdras/night-owl-vscode-theme/issues/139

**Comment by sdras** [comment] 2018-10-09 06:03
Yes, this should be fixed with that PR :) I'll close it out in the meantime but feel free to reopen if after that PR is in, it's still not right. Thanks for reporting!

**Closed by sdras** 2018-10-09 06:03 UTC
Labels: duplicate
