### ISSUE TITLE
Request: Sass syntax highlight == SCSS syntax highlight

### ISSUE THREAD

**Issue by moso** [sdras/night-owl-vscode-theme#68] opened 2018-05-31 12:27 UTC
I just stumpled upon this.

It seems Sass has correct syntax highlighting. However it would be nice if the Sass and SCSS would use the same syntax highlighting in this context, as it's basically the same thing, syntax highlight-wise.

Examples:

SCSS:
![https://dev.moso.io/img/code1.png](https://dev.moso.io/img/code1.png)

Sass:
![https://dev.moso.io/img/code2.png](https://dev.moso.io/img/code2.png)

**Comment by sdras** [comment] 2018-05-31 20:13
Thank you! I'll get it sorted soon and let you know when I do :)

**Comment by wistcc** [comment] 2018-06-04 22:28
Hey @moso, I would like to help to fix this but I'm not able to reproduce.

Those screenshots were taken from a file with the `.sass` extension and the other one from another file with the `.scss` extension?

Or is it a `.vue` file with different style tags like this:?
```
<style lang="sass">
.class {
  color: $color;
}
</style>

<style lang="scss">
.class {
  color: $color;
}
</style>
```

Or is it another thing?

Thanks!

**Comment by sdras** [comment] 2018-06-05 04:58
I can reproduce. Bug fix coming!

**Comment by moso** [comment] 2018-06-05 05:04
@wistcc It's a `.scss`-file, sorry for the plain explaination.

However the SCSS syntax doesn't have the same highlighting as Sass have, which can be seen if you change the language in the bottom right corner, and select Sass. The syntax highlighting then appears to be correct.

**Comment by sdras** [comment] 2018-06-06 02:55
This should be fixed! Please update.

**Closed by sdras** 2018-06-06 02:55 UTC

**Comment by moso** [comment] 2018-06-06 09:40
Perfect!

Thanks Sarah!
