### ISSUE TITLE
Please make a Light Theme

### ISSUE THREAD

**Issue by bgarrant** [sdras/night-owl-vscode-theme#129] opened 2018-08-09 11:07 UTC
This is such a great theme for night coding.  Any chance you can make a daytime version also with a light colored background?

**Comment by chibicode** [comment] 2018-08-10 20:09
Duplicate of https://github.com/sdras/night-owl-vscode-theme/issues/59 - please upvote there! 😉

**Closed** 2018-08-11 16:19 UTC
