### ISSUE TITLE
Focus color on secondary list

### ISSUE THREAD

**Issue by aputhin** [sdras/night-owl-vscode-theme#54] opened 2018-05-28 04:00 UTC
Hi! First of all, thanks for this incredible theme. It has been a blast to use.

I found an issue with list rendering. On the command list (cmd+shift+P), the focus (through keyboard navigation) indicator relies on a dotted border on the highlighted item:
<img width="702" alt="screen shot 2018-05-28 at 00 33 33" src="https://user-images.githubusercontent.com/13985684/40596510-b8ab7fbe-6211-11e8-9f25-5fc9f2830254.png">

But, on "secondary" lists, such as those generated by plugins, there is no dotted border, and the focus isn't really visible because `"list.focusBackground": "#5f7e9700"` means no opacity. Example from the 'Advanced New File' plugin (but I found it on other lists):
<img width="646" alt="screen shot 2018-05-28 at 00 40 43" src="https://user-images.githubusercontent.com/13985684/40596539-ee769156-6211-11e8-8a64-5643cf1dc00c.png">

I guess the way to fix this would be adding the dotted border on these lists too, and I would be happy to PR for it, but I honestly don't know how to.

**Comment by sdras** [comment] 2018-05-28 14:36
Ok, sounds good, I would definitely take a PR for it if you do want to hunt it down.

**Comment by aputhin** [comment] 2018-05-28 17:30
I've actually narrowed it down to a Mac OSX issue, as my workplace Linux environment _does_ render the dotted border correctly. But I'm now wondering whether this is a theme-related or vscode/electron issue.

Will investigate further later :grin:

**Comment by wistcc** [comment] 2018-05-29 22:54
Weird, I am not able to reproduce this and I'm also using Mac OSX.

**Comment by sdras** [comment] 2018-05-29 22:56
Neither am I, so I'm closing it out for now, but please feel free to reopen if we're mistaken and it's a theme-related issue :)

**Closed by sdras** 2018-05-29 22:56 UTC
