### ISSUE TITLE
Light Theme : CSS units are hard to read

### ISSUE THREAD

**Issue by praveenpuglia** [sdras/night-owl-vscode-theme#194] opened 2019-04-10 09:26 UTC
**Screenshots**
![image](https://user-images.githubusercontent.com/313363/55867761-bfaa1300-5ba0-11e9-8187-310321e9bb87.png)

**Version** : 1.1.2

Thanks for the lovely theme!

**Comment by sdras** [comment] 2019-04-11 11:44
Strange, in 1.1.2 I can't reproduce. Can you please restart Code and let me know if it persists? Thanks!

**Comment by praveenpuglia** [comment] 2019-04-11 12:15
My bad. It's a stylus file.

**Comment by sdras** [comment] 2019-04-12 08:55
Ah, ok that helps, thanks!

**Comment by sdras** [comment] 2019-04-12 09:01
I'm still seeing in the stylus files that it's fixed now :/ can you please try to restart vs code?

**Comment by praveenpuglia** [comment] 2019-04-12 09:30
I just tried this out and it happens with the no-italics theme. with italics it works just fine. screenshot for both.

## No Italics
![image](https://user-images.githubusercontent.com/313363/56027423-a9808c00-5d33-11e9-9680-d35447b004cb.png)

## Italics 
![image](https://user-images.githubusercontent.com/313363/56027449-b4d3b780-5d33-11e9-9517-1d536b54bc68.png)

**Comment by souljessi** [comment] 2019-05-06 05:40
hi,girl.

**Comment by sdras** [comment] 2019-09-16 14:14
@praveenpuglia it's just a matter of bringing a property from one file to the other but I'm low on time. If you or anyone else would like to PR, I can get it in. Otherwise it will be a little bit. Thanks!

**Comment by praveenpuglia** [comment] 2019-09-16 15:54
I'll try looking into it tonight

**Comment by sdras** [comment] 2019-10-06 20:20
Thanks @tvandort!

**Closed** 2019-10-06 20:19 UTC
Labels: good first issue, pr welcome
